services:
  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mariadb:/var/lib/mariadb